"""empty message

Revision ID: 238b2729ff3b
Revises: ff6b0c776a11
Create Date: 2021-02-06 23:44:14.601053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238b2729ff3b'
down_revision = 'ff6b0c776a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'price',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
