"""empty message

Revision ID: dfe8c33a18a7
Revises: 90c01b3a2b98
Create Date: 2021-04-03 14:20:27.775227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe8c33a18a7'
down_revision = '90c01b3a2b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'address',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=9999),
               existing_nullable=False)
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=9999),
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=9999),
               existing_nullable=False)
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=9999),
               existing_nullable=False)
    op.alter_column('orders', 'employee_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=9999),
               existing_nullable=True)
    op.alter_column('orders', 'transaction_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=9999),
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=9999),
               existing_nullable=False)
    op.alter_column('products', 'expiry',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=9999),
               existing_nullable=True)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=9999),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=9999),
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=9999),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('products', 'image',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('products', 'expiry',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('orders', 'transaction_id',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('orders', 'employee_id',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('employees', 'name',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('categories', 'description',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('addresses', 'address',
               existing_type=sa.String(length=9999),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
