"""empty message

Revision ID: ff6b0c776a11
Revises: 0cbdd03ba948
Create Date: 2021-02-06 23:31:57.019970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6b0c776a11'
down_revision = '0cbdd03ba948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'price',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
